package engine

import (
	"archive/zip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type projectManifest struct {
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	Version   string `json:"version"`
}

type workspaceManifest struct {
	Name      string `json:"name"`
	Root      string `json:"root"`
	CreatedAt string `json:"created_at"`
}

func sortedKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedPackageKeys(values map[string]PackageRecord) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func humanBytes(size int64) string {
	units := []string{"B", "KB", "MB", "GB"}
	value := float64(size)
	for i, unit := range units {
		if value < 1024 || i == len(units)-1 {
			return fmt.Sprintf("%.1f%s", value, unit)
		}
		value /= 1024
	}
	return fmt.Sprintf("%dB", size)
}

func writeJSONFile(path string, value any) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

func readJSONFile(path string, target any) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, target)
}

func projectManifestPath(root string) string {
	return filepath.Join(root, ".indus", "project.json")
}

func workspaceManifestPath(root string) string {
	return filepath.Join(root, ".indus", "workspace.json")
}

func ensureProject(root, name, version string) error {
	dirs := []string{
		root,
		filepath.Join(root, ".indus"),
		filepath.Join(root, "app"),
		filepath.Join(root, "build"),
		filepath.Join(root, "docs"),
		filepath.Join(root, "data"),
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}

	if err := writeJSONFile(projectManifestPath(root), projectManifest{
		Name:      name,
		CreatedAt: time.Now().Format(time.RFC3339),
		Version:   version,
	}); err != nil {
		return err
	}

	readme := filepath.Join(root, "README.md")
	if _, err := os.Stat(readme); os.IsNotExist(err) {
		content := fmt.Sprintf("# %s\n\nGenerated by INDUS Terminal v%s.\n", name, version)
		if err := os.WriteFile(readme, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func copyFile(source, target string) error {
	in, err := os.Open(source)
	if err != nil {
		return err
	}
	defer in.Close()

	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}

	out, err := os.Create(target)
	if err != nil {
		return err
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func copyTree(source, target string) error {
	return safeWalkDir(source, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		rel, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		destination := filepath.Join(target, rel)
		if entry.IsDir() {
			return os.MkdirAll(destination, 0o755)
		}
		return copyFile(path, destination)
	})
}

func directorySize(root string) (int64, int, error) {
	var total int64
	count := 0

	err := safeWalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		total += info.Size()
		count++
		return nil
	})

	return total, count, err
}

func sha256Digest(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()

	hash := sha256.New()
	if _, err := io.Copy(hash, file); err != nil {
		return "", err
	}
	return hex.EncodeToString(hash.Sum(nil)), nil
}

func zipDirectory(source, target string) error {
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	archive, err := os.Create(target)
	if err != nil {
		return err
	}
	defer archive.Close()

	writer := zip.NewWriter(archive)
	defer writer.Close()

	return filepath.Walk(source, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}

		rel, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}

		header, err := zip.FileInfoHeader(info)
		if err != nil {
			return err
		}
		header.Name = strings.ReplaceAll(rel, "\\", "/")
		header.Method = zip.Deflate

		entry, err := writer.CreateHeader(header)
		if err != nil {
			return err
		}

		file, err := os.Open(path)
		if err != nil {
			return err
		}
		defer file.Close()

		_, err = io.Copy(entry, file)
		return err
	})
}

func fileCountSnapshot(root string) (map[string]time.Time, error) {
	snapshot := map[string]time.Time{}
	err := safeWalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		snapshot[path] = info.ModTime()
		return nil
	})
	return snapshot, err
}

// symlinkChecker tracks visited paths to detect symlink loops
type symlinkChecker struct {
	visited map[string]bool
}

func newSymlinkChecker() *symlinkChecker {
	return &symlinkChecker{
		visited: make(map[string]bool),
	}
}

// check returns true if the path can be visited (not a loop), false otherwise
func (sc *symlinkChecker) check(path string) (bool, error) {
	// Get the absolute path with symlinks resolved
	absPath, err := filepath.EvalSymlinks(path)
	if err != nil {
		// If we can't resolve symlinks, it might be a broken link or permission issue
		// Allow the operation to continue and let the caller handle the error
		return true, nil
	}

	// Check if we've already visited this resolved path
	if sc.visited[absPath] {
		return false, nil
	}

	// Mark as visited
	sc.visited[absPath] = true
	return true, nil
}

// safeWalkDir is a safer version of filepath.WalkDir that detects symlink loops
func safeWalkDir(root string, fn func(path string, entry fs.DirEntry, err error) error) error {
	checker := newSymlinkChecker()

	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return fn(path, entry, err)
		}

		// Check for symlink loops
		if entry.Type()&fs.ModeSymlink != 0 || entry.IsDir() {
			canVisit, checkErr := checker.check(path)
			if checkErr != nil {
				return fn(path, entry, checkErr)
			}
			if !canVisit {
				// Skip this path - it's a symlink loop
				if entry.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}
		}

		return fn(path, entry, err)
	})
}
